"""Second Migration

Revision ID: c0596f16a69a
Revises: a4d21d050a53
Create Date: 2026-06-16 08:09:04.240512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0596f16a69a'
down_revision: Union[str, Sequence[str], None] = 'a4d21d050a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'last_message_id')
    # ### end Alembic commands ###
